export const POST_CHAT_MESSEAGE_PENDING   = "POST_CHAT_MESSEAGE_PENDING"
export const POST_CHAT_MESSEAGE_SUCCESS   = "POST_CHAT_MESSEAGE_SUCCESS"
export const POST_CHAT_MESSEAGE_ERROR     = "POST_CHAT_MESSEAGE_ERROR"
export const GET_CHAT_MESSEAGE_SUCCESS    = "GET_CHAT_MESSEAGE_SUCCESS"